---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_listen_port_ssl: 443
    apache_create_vhosts: true
    apache_ignore_missing_ssl_certificate: false
    apache_vhosts_filename: "vhosts.conf"
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"
    apache_vhosts_individual:
      - servername: "local.dev"
        documentroot: "/var/www/html"
        vhostname: "local.dev"
      - servername: "myfedora.org"
        documentroot: "/var/www/html"
        vhostname: "myfedora.org"
      - servername: "mycentos.net"
        documentroot: "/var/www/html"
        vhostname: "mycentos.net"
        directoryindex: "mycentos.txt"
      - servername: "myubuntu.com"
        documentroot: "/var/www/html"
        vhostname: "myubuntu.com"
      - servername: "myubuntu.com"
        documentroot: "/var/www/html"
        vhostname: "myubuntu.com-ssl"
        directoryindex: "myubuntu.txt"
        certificate_file: "/root/www.ubuntu.com.crt"
        certificate_key_file: "/root/cert.key"
      - servername: "local.org"
        documentroot: "/var/www/html"
        vhostname: "local.org-ssl"
        certificate_file: "/root/local.crt"
        certificate_key_file: "/root/cert.key"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: install website index files
      copy:
        src: "files/{{ item }}"
        dest: "/var/www/html/{{ item }}"
      with_items:
        - "mycentos.txt"
        - "myubuntu.txt"
    - name: install website certs and keys
      copy:
        src: "files/{{ item }}"
        dest: "/root/{{ item }}"
      with_items:
        - "www.ubuntu.com.crt"
        - "cert.key"

  roles:
    - role: ansible-role-apache
